name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 


  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to EC2 instance
  run: |
    scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./var/www/html/ ubuntu@13.235.45.64:~/var/www/html/
    ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@13.235.45.64 "cd ~/var/www/html/ && ./deploy_script.sh"
  shell: bash
  env:
    AWS_DEFAULT_REGION: ap-south-1
    AWS_REGION: ap-south-1
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
