name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 8.1


  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to EC2 instance
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r ./var/www/html/ ubuntu@13.235.45.64:~/var/www/html/
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@13.235.45.64 "cd ~/var/www/html/ && ./deploy_script.sh"

