name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Replace with your desired PHP version

   
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Connect to AWS EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }} # Replace with your EC2 instance IP or hostname
        username: ${{ secrets.AWS_EC2_USERNAME }} # Replace with your EC2 instance username
        key: ${{ secrets.AWS_EC2_PRIVATE_KEY }} # Replace with your EC2 instance private key
        port: 22
        
