name: php ci cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync sshpass
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy code on ec2
        run: |
          sshpass -p "${{ secrets.SSH_PRIVATE_KEY_PATH }}" rsync -e 'ssh -o StrictHostKeyChecking=no' -avz --delete-after --exclude '.git/' $GITHUB_WORKSPACE/path/to/source/ ubuntu@13.235.45.64:/var/www/html
